import { signOutAction, updateProfileAction } from "@/app/actions";
import { requireUser } from "@/lib/auth/session";
import { CONFIDENCE_COPY, type CompetitiveIdentity, type PlayerCompetitiveState, type RsiConfidenceLevel } from "@/lib/competitive/identity";
import { createClient } from "@/lib/supabase/server";

const municipalities = ["Angra dos Reis","Aperibé","Araruama","Areal","Armação dos Búzios","Arraial do Cabo","Barra do Piraí","Barra Mansa","Belford Roxo","Bom Jardim","Bom Jesus do Itabapoana","Cabo Frio","Cachoeiras de Macacu","Cambuci","Campos dos Goytacazes","Cantagalo","Carapebus","Cardoso Moreira","Carmo","Casimiro de Abreu","Comendador Levy Gasparian","Conceição de Macabu","Cordeiro","Duas Barras","Duque de Caxias","Engenheiro Paulo de Frontin","Guapimirim","Iguaba Grande","Itaboraí","Itaguaí","Italva","Itaocara","Itaperuna","Itatiaia","Japeri","Laje do Muriaé","Macaé","Macuco","Magé","Mangaratiba","Maricá","Mendes","Mesquita","Miguel Pereira","Miracema","Natividade","Nilópolis","Niterói","Nova Friburgo","Nova Iguaçu","Paracambi","Paraíba do Sul","Paraty","Paty do Alferes","Petrópolis","Pinheiral","Piraí","Porciúncula","Porto Real","Quatis","Queimados","Quissamã","Resende","Rio Bonito","Rio Claro","Rio das Flores","Rio das Ostras","Rio de Janeiro","Santa Maria Madalena","Santo Antônio de Pádua","São Fidélis","São Francisco de Itabapoana","São Gonçalo","São João da Barra","São João de Meriti","São José de Ubá","São José do Vale do Rio Preto","São Pedro da Aldeia","São Sebastião do Alto","Sapucaia","Saquarema","Seropédica","Silva Jardim","Sumidouro","Tanguá","Teresópolis","Trajano de Moraes","Três Rios","Valença","Varre-Sai","Vassouras","Volta Redonda"];

const providers = [
  { key: "steam", label: "Steam", required: true },
  { key: "faceit", label: "FACEIT", required: false },
] as const;

type SearchParams = Promise<{ steam?: string; faceit?: string; profile?: string; message?: string }>;

export default async function PerfilPage({ searchParams }: { searchParams: SearchParams }) {
  const params = await searchParams;
  const user = await requireUser();
  const supabase = await createClient();
  const [{ data: profile }, { data: identities }, { data: competitiveState }] = await Promise.all([
    supabase.from("profiles").select("username, display_name, avatar_url, bio, city, state_code").eq("id", user.id).maybeSingle(),
    supabase.from("competitive_identities").select("provider, external_id, external_username, status, data_available, verified_at, last_verified_at").eq("user_id", user.id),
    supabase.from("player_competitive_state").select("rsi, confidence_score, confidence_level, faceit_ban_detected, competitive_lock_reason, calculated_at").eq("user_id", user.id).maybeSingle(),
  ]);

  const identityList = (identities ?? []) as CompetitiveIdentity[];
  const identityByProvider = new Map(identityList.map((identity) => [identity.provider, identity]));
  const state = competitiveState as PlayerCompetitiveState | null;
  const confidence = CONFIDENCE_COPY[(state?.confidence_level ?? "low") as RsiConfidenceLevel];
  const linked = params.steam === "linked" || params.faceit === "linked";
  const failed = params.steam === "error" || params.faceit === "error";
  const location = profile?.city === "N/A" || profile?.city === "NA" ? "Fora do Rio de Janeiro (N/A)" : profile?.city ? `${profile.city}, ${profile.state_code ?? "RJ"}` : "Ainda não informada";

  return <main className="min-h-screen bg-[#050505] px-6 py-16 text-white"><section className="mx-auto max-w-4xl space-y-6">
    <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-8">
      <div className="flex items-start justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-cyan-400">Minha conta</p><h1 className="mt-3 text-3xl font-black">{profile?.display_name ?? user.email}</h1><p className="mt-2 text-white/50">@{profile?.username ?? "player"}</p></div><span className="rounded-lg border border-white/10 px-3 py-2 text-[10px] font-black uppercase tracking-widest text-white/40">Perfil</span></div>
      <div className="mt-8 grid gap-4 text-sm text-white/65 sm:grid-cols-3"><div><span className="block text-white/35">E-mail</span>{user.email}</div><div><span className="block text-white/35">Localização</span>{location}</div><div><span className="block text-white/35">RIO ID</span>Perfil competitivo</div></div>
      <details className="mt-8 rounded-xl border border-cyan-400/20 bg-cyan-400/[0.03] p-5"><summary className="flex cursor-pointer list-none items-center justify-between rounded-lg border border-cyan-400/30 bg-cyan-400/10 px-4 py-3 text-sm font-black text-cyan-300 transition hover:bg-cyan-400/15"><span>EDITAR MEU PERFIL</span><span className="text-lg leading-none">＋</span></summary><form action={updateProfileAction} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm text-white/60">Nome de exibição<input name="display_name" required minLength={2} maxLength={60} defaultValue={profile?.display_name ?? ""} className="mt-2 w-full rounded-lg border border-white/10 bg-[#080808] px-4 py-3 text-white outline-none focus:border-cyan-400" /></label><label className="text-sm text-white/60">Nome de usuário<input name="username" required minLength={3} maxLength={24} defaultValue={profile?.username ?? ""} className="mt-2 w-full rounded-lg border border-white/10 bg-[#080808] px-4 py-3 text-white outline-none focus:border-cyan-400" /><span className="mt-1 block text-xs text-white/30">3–24 caracteres: letras, números e _.</span></label><label className="text-sm text-white/60 sm:col-span-2">Município<select name="city" defaultValue={profile?.city === "NA" ? "N/A" : (profile?.city ?? "")} required className="mt-2 w-full rounded-lg border border-white/10 bg-[#080808] px-4 py-3 text-white outline-none focus:border-cyan-400"><option value="">Selecione seu município</option><option value="N/A">Não sou do Rio de Janeiro (N/A)</option>{municipalities.map((city) => <option key={city} value={city}>{city}</option>)}</select></label><button className="w-fit rounded-lg bg-cyan-400 px-5 py-3 text-xs font-black uppercase tracking-wide text-black transition hover:bg-cyan-300 sm:col-span-2">SALVAR ALTERAÇÕES</button></form></details>
    </div>

    {params.profile === "saved" ? <div className="rounded-xl border border-emerald-400/30 bg-emerald-400/5 p-4 text-sm text-emerald-200">Perfil atualizado com sucesso.</div> : null}{params.profile === "error" ? <div className="rounded-xl border border-red-400/30 bg-red-400/5 p-4 text-sm text-red-200">{params.message ?? "Não foi possível atualizar seu perfil."}</div> : null}{linked ? <div className="rounded-xl border border-emerald-400/30 bg-emerald-400/5 p-4 text-sm text-emerald-200">Conta competitiva vinculada com sucesso.</div> : null}{failed ? <div className="rounded-xl border border-red-400/30 bg-red-400/5 p-4 text-sm text-red-200">Não foi possível concluir a vinculação. Tente novamente.</div> : null}

    <section className="rounded-2xl border border-cyan-400/20 bg-cyan-400/[0.03] p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.25em] text-cyan-400">Competitive Identity</p><h2 className="mt-3 text-2xl font-black">Sua identidade competitiva</h2><p className="mt-3 max-w-xl text-sm leading-6 text-white/55">Steam é a identidade obrigatória. FACEIT fortalece a confiança dos dados usados pelo RSI.</p></div><div className="rounded-xl border border-white/10 bg-black/20 px-5 py-4 sm:min-w-40"><span className="block text-xs font-bold uppercase tracking-wider text-white/35">RSI Confidence</span><strong className="mt-1 block text-2xl font-black text-cyan-300">{confidence.label}</strong><span className="text-xs text-white/40">{state?.confidence_score ?? 0}/100</span></div></div><p className="mt-6 text-sm text-white/50">{confidence.description}</p><div className="mt-6 grid gap-3 md:grid-cols-2">{providers.map((provider) => { const identity = identityByProvider.get(provider.key); const verified = identity?.status === "verified"; const linkHref = provider.key === "steam" ? "/api/competitive/steam/start" : "/api/competitive/faceit/start"; return <div key={provider.key} className="rounded-xl border border-white/10 bg-black/20 p-5"><div className="flex items-center justify-between gap-3"><strong>{provider.label}</strong><span className={`text-xs font-bold uppercase tracking-wider ${verified ? "text-emerald-300" : "text-white/35"}`}>{verified ? "Verificada" : identity ? "Pendente" : "Não vinculada"}</span></div><p className="mt-3 text-sm leading-6 text-white/45">{identity?.external_username ? identity.external_username : provider.required ? "Vinculação obrigatória para participar do ambiente competitivo." : "Vincule sua conta FACEIT para fortalecer sua identidade competitiva."}</p>{!verified ? <a href={linkHref} className="mt-5 inline-flex rounded-lg bg-cyan-400 px-4 py-2 text-xs font-black uppercase tracking-wide text-black transition hover:bg-cyan-300">Vincular {provider.label}</a> : null}{verified ? <p className="mt-5 text-xs text-emerald-300/80">Identidade verificada.</p> : null}</div>; })}</div>{state?.competitive_lock_reason ? <div className="mt-6 rounded-xl border border-red-400/30 bg-red-400/5 p-4 text-sm text-red-200">Conta competitiva bloqueada: {state.competitive_lock_reason}</div> : null}</section><form action={signOutAction}><button className="rounded-lg border border-white/15 px-5 py-3 text-sm font-bold hover:bg-white/5">SAIR</button></form></section></main>;
}
