import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { newsArticles } from "./articles";

export default async function NoticiasPage() {
  const supabase = await createClient();
  const { data } = await supabase.from("news_articles").select("slug, title, excerpt, published_at, cover_image_url").eq("status", "published").lte("published_at", new Date().toISOString()).order("published_at", { ascending: false }).limit(12);
  const liveArticles = data?.map((article) => ({ ...article, category: "RIO ESPORTS", read: "Leitura" })) ?? [];
  const articles = liveArticles.length ? liveArticles : newsArticles.map((article) => ({ ...article, published_at: null, cover_image_url: null }));
  const featured = articles[0];
  const stories = articles.slice(1);

  return <main className="min-h-screen bg-[#050505] text-white">
    <header className="border-b border-white/10"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-6 py-5 lg:px-8"><Link href="/" className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-white font-black text-black">R</div><div><div className="text-lg font-black tracking-tight">RIO<span className="text-cyan-400">ESPORTS</span></div><div className="text-[9px] uppercase tracking-[0.25em] text-white/40">Competitive Community</div></div></Link><nav className="hidden items-center gap-7 text-sm font-medium text-white/55 md:flex"><Link href="/">INÍCIO</Link><Link className="text-white" href="/noticias">NOTÍCIAS</Link><Link href="/matchmaking">MATCHMAKING</Link><Link href="/perfil">PERFIL</Link></nav><Link href="/login" className="rounded-lg border border-white/15 px-4 py-2 text-sm font-semibold">Entrar</Link></div></header>
    <section className="mx-auto max-w-7xl px-6 py-16 lg:px-8 lg:py-24"><div className="flex flex-col justify-between gap-8 border-b border-white/10 pb-10 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.35em] text-cyan-400">Central editorial</p><h1 className="mt-4 text-5xl font-black tracking-[-0.04em] sm:text-7xl">NOTÍCIAS<span className="text-cyan-400">.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-white/50">Esports, jogos, comunidade e tudo o que movimenta o cenário competitivo.</p></div><p className="text-xs font-bold uppercase tracking-[0.2em] text-white/30">RIO ESPORTS JOURNAL</p></div>
    {featured && <section className="grid gap-5 border-b border-white/10 py-10"><article className="group relative min-h-[420px] overflow-hidden rounded-2xl border border-cyan-400/20 bg-gradient-to-br from-cyan-400/[0.12] via-[#0a0a0a] to-[#050505] p-8 lg:p-12"><div className="absolute -right-20 -top-20 h-72 w-72 rounded-full bg-cyan-400/15 blur-[100px]" />{featured.cover_image_url && <div className="absolute inset-0 bg-cover bg-center opacity-20" style={{ backgroundImage: `url(${featured.cover_image_url})` }} />}<div className="relative flex h-full flex-col justify-end"><span className="mb-auto inline-flex w-fit rounded-full bg-cyan-400/10 px-3 py-1 text-[10px] font-black tracking-[0.18em] text-cyan-300">{featured.category}</span><p className="mt-20 text-xs font-bold tracking-wider text-white/35">{featured.published_at ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium" }).format(new Date(featured.published_at)) : "RIO ESPORTS"}</p><h2 className="mt-4 max-w-3xl text-3xl font-black leading-tight sm:text-5xl">{featured.title}</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-white/55 sm:text-base">{featured.excerpt}</p><Link href={`/noticias/${featured.slug}`} className="mt-8 w-fit text-xs font-black uppercase tracking-[0.2em] text-cyan-300">Ler matéria →</Link></div></article></section>}
    <section className="py-16"><div className="mb-8 flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.25em] text-white/30">Atualizações</p><h2 className="mt-3 text-3xl font-black">Últimas notícias</h2></div><span className="text-xs text-white/30">MAIS RECENTES</span></div><div className="grid gap-4 md:grid-cols-2">{stories.map((story, index) => <article key={story.slug} className="group rounded-xl border border-white/10 bg-white/[0.02] p-6 transition hover:border-cyan-400/35 hover:bg-cyan-400/[0.025]"><div className="flex items-center justify-between"><span className="text-[10px] font-black tracking-[0.18em] text-cyan-400">{story.category}</span><span className="text-xs text-white/25">{story.read}</span></div><div className="mt-8 flex gap-5"><span className="text-3xl font-black text-white/10">{String(index + 1).padStart(2, "0")}</span><div><h3 className="text-xl font-black leading-snug">{story.title}</h3><p className="mt-3 text-sm leading-6 text-white/45">{story.excerpt}</p><Link href={`/noticias/${story.slug}`} className="mt-6 inline-block text-xs font-black uppercase tracking-wider text-white/70 transition group-hover:text-cyan-300">Continuar lendo →</Link></div></div></article>)}</div></section></section>
    <footer className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 px-6 py-8 text-xs text-white/30 sm:flex-row lg:px-8"><span>© 2026 RIO ESPORTS</span><span>RIO ESPORTS JOURNAL</span></div></footer>
  </main>;
}
