import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

export default async function NoticiasPage() {
  const supabase = await createClient();
  const { data: posts } = await supabase.from("news_posts").select("id, title, slug, excerpt, cover_image_url, published_at").eq("status", "published").lte("published_at", new Date().toISOString()).order("published_at", { ascending: false });
  const featured = posts?.[0];
  const stories = posts?.slice(1) ?? [];
  return <main className="min-h-screen bg-[#050505] text-white"><header className="border-b border-white/10"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-6 py-5 lg:px-8"><Link href="/" className="text-lg font-black">RIO<span className="text-cyan-400">ESPORTS</span></Link><nav className="hidden gap-7 text-sm text-white/55 md:flex"><Link href="/">INÍCIO</Link><Link className="text-white" href="/noticias">NOTÍCIAS</Link><Link href="/matchmaking">MATCHMAKING</Link></nav><Link href="/login" className="rounded-lg border border-white/15 px-4 py-2 text-sm">Entrar</Link></div></header><section className="mx-auto max-w-7xl px-6 py-16 lg:px-8"><div className="border-b border-white/10 pb-10"><p className="text-xs font-black uppercase tracking-[0.35em] text-cyan-400">Central editorial</p><h1 className="mt-4 text-5xl font-black sm:text-7xl">NOTÍCIAS<span className="text-cyan-400">.</span></h1><p className="mt-5 max-w-xl text-white/50">Esports, jogos, comunidade e tudo o que movimenta o cenário competitivo.</p></div>{featured ? <section className="mt-10"><Link href={`/noticias/${featured.slug}`} className="block rounded-2xl border border-cyan-400/20 bg-gradient-to-br from-cyan-400/[0.12] via-[#0a0a0a] to-[#050505] p-8 lg:p-12"><p className="text-xs font-bold text-white/35">{featured.published_at ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "long" }).format(new Date(featured.published_at)) : ""}</p><h2 className="mt-4 max-w-4xl text-3xl font-black sm:text-5xl">{featured.title}</h2><p className="mt-5 max-w-2xl leading-7 text-white/55">{featured.excerpt || "Leia a matéria completa."}</p><span className="mt-8 inline-block text-xs font-black uppercase tracking-[0.2em] text-cyan-300">Ler matéria →</span></Link></section> : <div className="mt-10 rounded-2xl border border-dashed border-white/10 py-16 text-center text-white/35">A central editorial está pronta para receber as primeiras notícias.</div>}<section className="py-16"><h2 className="text-3xl font-black">Últimas notícias</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{stories.map((post, index) => <Link key={post.id} href={`/noticias/${post.slug}`} className="rounded-xl border border-white/10 bg-white/[0.02] p-6 transition hover:border-cyan-400/35"><span className="text-3xl font-black text-white/10">0{index + 1}</span><h3 className="mt-6 text-xl font-black">{post.title}</h3><p className="mt-3 text-sm leading-6 text-white/45">{post.excerpt || "Leia a notícia completa."}</p><span className="mt-6 inline-block text-xs font-black text-cyan-300">Continuar lendo →</span></Link>)}</div></section></section></main>;
}
