import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export default async function AdminModerationPage() {
  const supabase = await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/login"); const {data:isAdmin}=await supabase.rpc("is_current_platform_admin"); if(!isAdmin)redirect("/");
  const [{data:users},{data:admins},{data:penalties}]=await Promise.all([supabase.from("profiles").select("id,display_name,username,created_at").order("created_at",{ascending:false}).limit(100),supabase.from("platform_admins").select("user_id,role,profiles(display_name,username)"),supabase.from("user_penalties").select("id,user_id,penalty_type,reason,expires_at,revoked_at,created_at").order("created_at",{ascending:false}).limit(100)]);
  const active=penalties?.filter(p=>!p.revoked_at&&(!p.expires_at||new Date(p.expires_at)>new Date())).length??0;
  return <main className="min-h-screen bg-zinc-950 px-4 py-8 text-zinc-100 sm:px-8"><div className="mx-auto max-w-6xl"><Link href="/admin" className="text-sm text-cyan-400">← Administração</Link><h1 className="mt-3 text-3xl font-black">Usuários e moderação</h1><section className="mt-8 grid gap-4 md:grid-cols-3"><Stat label="Usuários" value={users?.length??0}/><Stat label="Administradores" value={admins?.length??0}/><Stat label="Penalidades ativas" value={active}/></section><section className="mt-8 rounded-2xl border border-zinc-800 bg-zinc-900/60"><h2 className="border-b border-zinc-800 p-6 font-bold">Histórico disciplinar</h2><div className="divide-y divide-zinc-800">{penalties?.map(p=>{const profile=users?.find(u=>u.id===p.user_id);return <div key={p.id} className="p-5"><div className="flex justify-between gap-4"><div><p className="font-bold">{profile?.display_name??profile?.username??"Usuário"}</p><p className="mt-2 text-sm text-zinc-400">{p.reason}</p></div><span className="h-fit rounded-full bg-red-500/10 px-2 py-1 text-xs text-red-300">{p.penalty_type}</span></div></div>})}{!penalties?.length&&<p className="p-8 text-center text-zinc-500">Nenhuma penalidade registrada.</p>}</div></section></div></main>;
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-xl border border-zinc-800 bg-zinc-900/60 p-5"><p className="text-sm text-zinc-400">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>;}